#!/usr/bin/env ruby


require 'yaml'
require 'erb'

# generic variables
@config = YAML.load_file('environment_del.yaml')
@nodes = @config['nodes']

#####################################################################
# Create config files for each node
#####################################################################

def set_node_template_vars(values)
    @Eth_Etherbase = values['geth']['Eth_Etherbase']
    @Node_UserIdent = values['geth']['Node_UserIdent']
    @Node_DataDir = values['geth']['Node_DataDir']
    @Node_HTTPPort = values['geth']['Node_HTTPPort']
    @Node_WSPort = values['geth']['Node_WSPort']
    @NodeP2P_ListenAddr = values['geth']['NodeP2P_ListenAddr']
    @NodeP2P_DiscoveryAddr = values['geth']['NodeP2P_DiscoveryAddr']
    @Dashboard_Port = values['geth']['Dashboard_Port']
    @Dashboard_Refresh = values['geth']['Dashboard_Refresh']
    @replicas = values['k8s']['replicas']
    return
end

#####################################################################
# genesis
#####################################################################
File.open('genesis.json', 'w') do |f|
    f.puts ERB.new(File.read('erb/genesis.json.erb'), nil, '-').result
end


#####################################################################
# nodes
#####################################################################

@nodes.each do |node|
    set_node_template_vars(node.values.first)
    File.open("#{@Node_UserIdent}.toml", 'w') do |f|
        f.puts ERB.new(File.read('nodes/node.toml.erb'), nil, '-').result
    end
end

#####################################################################
# nodes config
#####################################################################
File.open('yamlDel/03_nodes.yaml', 'w') do |f|
    f.puts ERB.new(File.read('erb/03_nodes.yaml.erb'), nil, '-').result
end
